# DataSource Config
spring:
  datasource:
    url: jdbc:mysql://xx:3306/MyTest
    username: root
    password: xx

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志